### PR TITLE
Updated Compose to 1.6.0-rc02, also updated Pages Composable API

### LINKED ISSUE #461: [3.0] Revert Pages(pages) argument back to just ChildPages, once Compose is updated to 1.6.0
Wait for Compose version `1.6.0`. Keep in mind (verify) the following issue: https://issuetracker.google.com/issues/294751365.

Derived from #444.

### PR DESCRIPTION
**Pull request by arkivanov**
Closes #461.

### CODE REVIEW

**Comment by chrisjenx** [comment]
Can we get a release with this? As alpha6 isn't binary compatible with 1.6.0-rc0x until this is updated :(

**Comment by arkivanov** [comment]
Could you elaborate why is it binary compatibility? We're there breaking changes on Compose?

**Comment by chrisjenx** [comment]
See: https://github.com/JetBrains/compose-multiplatform/releases/tag/v1.6.0-rc01  "Could not find..."

**Comment by chrisjenx** [comment]
Oh ignore me, looks like it's Chris's material3-window-size-class-multiplatform. I'll ping him to cut a release.

**Comment by arkivanov** [comment]
Thanks for the update! I will release an update anyway in the coming days.

**Pull request merged**
