### PR TITLE
add experimental js support to compose-jb extension

### PR DESCRIPTION
**Pull request by sproctor**

### CODE REVIEW

**Comment by arkivanov** [comment]
Thanks! Hopefully will go with the next release.

**Comment by arkivanov** [comment]
Unfortunately, I faced critical Compose compiler bugs while working on a sample for Compose for Web.

Most critical are:

- https://github.com/JetBrains/compose-jb/issues/2612
- https://github.com/JetBrains/compose-jb/issues/2688

Basically, it's not possible to run a Canvas Compose app that depends on `extensions-compose-jetbrains` module without changes in the module. We have to wait for Compose for Web to become more stable before supporting it.

**Comment by arkivanov** [comment]
Never mind, I found some workarounds. Already released in `1.0.0.` Thanks again!

**Comment by sproctor** [comment]
That was fast! I don't see it in 1.0.0 though.

**Comment by arkivanov** [comment]
Experimental Compose support is released separately - https://github.com/arkivanov/Decompose/releases/tag/1.0.0-compose-experimental

**Pull request merged**
