### PR TITLE
Add flattened value

### PR DESCRIPTION
**Pull request by tieskedh**
When the same `valueT` is set, the observer is resubscribed. 

pro:
- This is consistent with not filtering out duplicated values.
- This also enables to emit a sequence of events after subscribing.

con:
- It is less efficient.

### CODE REVIEW

**Comment by arkivanov** [comment]
Could you please describe any use cases for this?

**Comment by tieskedh** [comment]
Combining multiple store-states into a single state for the page.

In my case:
I have a splitpane with on the right items with tags.
On the left, you can create searches (name, coupled to multiple labels).
By pressing on the search, the list on the right changes.

With flatten, I can combine both to a filtered list.

**Comment by arkivanov** [comment]
Thanks for the use case! It appears to be quite the same as in discussion #97. It's advised to use a reactive library, e.g. `Flow` from coroutines, or `Observable` from Reaktive. They both have a bunch of operators for combining multiple streams.

E.g. if you are using `MVIKotlin`, here is what you can do:

```
// For coroutines
val models: Value<Model> = 
    combine(store1.states, store2.states) { state1, state2 -> 
        // Combine two states into one model
    }.asValue(...)

// For Reaktive
val models: Value<Model> = 
    combineLatest(store1.states, store2.states) { state1, state2 -> 
        // Combine two states into one model
    }.asValue(...)
```

Here is an example of the `Observable` -> `Value` converter. It should be very similar for coroutines.
```kotlin
fun <T : Any> Observable<T>.asValue(initialValue: T, lifecycle: Lifecycle): Value<T> {
    val value = MutableValue(initialValue)
    val disposable = subscribe { value.value = it }
    lifecycle.doOnDestroy(disposable::dispose)

    return value
}
```

Would this work for you?

**Comment by arkivanov** [comment]
Closing this for now. It's advised to combine streams using `Flow` (coroutines) or `Observable` (Reaktive).

**Pull request closed without merging**
