### PR TITLE
Merge v2.1 branch to v2.1-experimental-compose

### PR DESCRIPTION
**Pull request by arkivanov**

### CODE REVIEW

**Comment by malliaridis** [comment]
I think the commit 1dad348ae1ad7e3b509e8d3571abfe90b58d89fc can be reverted in this PR, since the `extensions-jetpack-compose` package does not exist anymore in the `experimental-compose`.

**Comment by malliaridis** [comment]
Should `cacheKind` from `gradle.properties` be also removed in this version? Or is it still needed?

**Comment by arkivanov** [comment]
> I think the commit https://github.com/arkivanov/Decompose/commit/1dad348ae1ad7e3b509e8d3571abfe90b58d89fc can be reverted in this PR, since the extensions-jetpack-compose package does not exist anymore in the experimental-compose.

I will address this, thanks. We need to only remove the new `PagesTest`, everything else was automatically removed on merge.

> Should cacheKind from gradle.properties be also removed in this version? Or is it still needed?

I will verify this first. There is an open PR for this: #126.

Currently I'm having issues with building the `app-js-compose` module on `v2.1-experimental-compose` branch after merging `v2.1`. See: https://youtrack.jetbrains.com/issue/KT-60852.

**Comment by malliaridis** [comment]
> Currently I'm having issues with building the app-js-compose module on v2.1-experimental-compose branch after merging v2.1.

We could also consider migrating the sample app to a multiplatform app, since the `kotlin-js` plugin is deprecated since 1.8.0. Perhaps this would resolve the resolution issue?

**Comment by arkivanov** [comment]
> We could also consider migrating the sample app to a multiplatform app, since the kotlin-js plugin is deprecated since 1.8.0. Perhaps this would resolve the resolution issue?

As far I can see, the Compose Web sample app already uses `kotlin-multiplatform` plugin?

https://github.com/arkivanov/Decompose/blob/6f5f4900f237dfc125f58832d4e6844e39cad204/sample/app-js-compose/build.gradle.kts#L6

**Comment by malliaridis** [comment]
The deprecation warning was coming from the `app-js` module where `id("org.jetbrains.kotlin.js")` is still in use. I wasn't sure at first if this is relevant, but in the [release notes of 1.9.0](https://kotlinlang.org/docs/whatsnew19.html#deprecation-of-the-kotlin-js-gradle-plugin) they mentioned the deprecation too.

> Configure project :sample:app-js
project ':sample:app-js', target js (js), compilation allowed: true
w: 'kotlin-js' Gradle plugin is deprecated and will be removed in the future. 
Please use 'kotlin("multiplatform")' plugin with a 'js()' target instead. See the migration guide: https://kotl.in/t6m3vu

**Comment by arkivanov** [comment]
Oh right! It would be nice to replace it then! Though, the original issue was a build failure of the `app-js-compose` module, which uses `kotlin-multiplatform`.

**Pull request merged**
